name: Gh-Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - name: Installing Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Building web app
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
          baseHref: /Tableau/
      - name: Building apk
        run: flutter build apk --target-platform android-arm64,android-arm --split-debug-info=build/tableau_debug_build_info/ --tree-shake-icons
      - uses: actions/upload-artifact@v3
        with:
          name: apk-release
          path: build/app/outputs/apk/release/app-release.apk
